language: ruby
cache: bundler

script: bundle exec rake site:deploy

notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://wdk.se/webhook
    on_success: always
    on_failure: never
env:
  global:
    secure: "KQHkSnDaeb3KcLR1fpGFvwLh8DqnDTQ+MTsV4I3AKSaErRXUZ/1Km+PiHjblge/bAUF9sAfJ91xjTeDw1e9qCTpWugFzUtZYx22fHyPRHcVpxtmYUCgQh7bxdnddCINtP++QNiDP0bhba38+LhCgcp+GcSeJMZ4r+gCjofn3vOA="
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
