language: ruby
cache: bundler
sudo: false

script: bundle exec rake site:deploy

notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://wdk.se/webhook
    on_success: always
    on_failure: never
env:
  global:
    - secure: "m6PxVMHH9yXF0wFRX+LLk8Oh/6x9HbolTXIoNy0TiZkiyvM0eTnzu3sZnLXZLDKLYyO7JQxF36w26VFgdGl6/OriEn8Z4fhLMYVdENZcMnrG+RQxzdtPIstHCt5hyFjqXpxrfvPubUibtO1fWEMhRDQXoZgkfCqVfCnlSKrYfis="
    - secure: "dsxch7wvZM+FI7O/h3SC6DdlA+fni0Wz2dgmKRvSRiMMRt1za37qSyFXK9QrwoWh31muKcmMq/RZ488eXDokROiP4n1lEAvJafM0IRvdx2joMqTeqmrptm4+0hEHUWfD8WS3gxtO5IGRca9KQ0BtS4LhFDq3ld9uaAzXXd+fCyU="
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
