language: ruby
cache: bundler

script: bundle exec rake site:deploy

env:
  global:
    secure: J+la+gLIi60xeK3515/mCu4XRCPqTjhgSQZMDFYl1yCU0luGPjbf2KXXRaRCCh31xpQ1F+YB4cZTc8T/WU2+p1fTbjIxU0RGJCB7qV9WGBgU1LTRz51E4+lazLMIclsAk+9xqO1PYUagRIVkoZ9WMv4laqoeYH2c6Z5YB1OPHtM=
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
