safe: false
lsi: false
markdown: kramdown
pygments: true

title:            Webbdesignkurser
description: "Hur gör man en hemsida? Få svaret på Webbdesignkurser där alla kurser är gratis och lätta att komma igång med!"
url: http://localhost:4000
searchUrl: /search.json

destination: ./_site/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: Webbdesignkurser
repo: website
branch: master

disqus_shortname: webbdesignkurser

permalink:   /:categories/:title/

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

assets:
  js_compressor:  yui
  css_compressor: yui
  gzip: false
  sources:
    - _assets/js
    - _assets/js/vendor
    - _assets/css
    - _assets/css/vendor
    - assets/images

gems: [jekyll-assets]

lunr_search:
  excludes: [sitemap.xml,feed.xml]
# display_path: "website/assets"


local: true

courses:
  - title: Grunderna i Webbdesign
    id: webbdesign
    description: Efter den här kursen så kommer du att kunna utveckla och publicera en fungerande hemsida.
    class: webbdesign
    image: thumbnail_grunderna-i-webbdesign.jpg
  - title: Responsiv design
    id: responsiv-design
    description: Hur designar man för alla plattformar? Här går vi igenom alla alternativen som finns.
    class: responsivDesign
    image: thumbnail_responsiv-design.jpg
  - title: Grunderna i Grafisk design
    id: grafisk-design
    description: En bra hemsida kräver även bra design. Här visar vi grunderna i bildhantering.
    class: grafiskDesign
    image: thumbnail_grafisk-design.jpg
  - title: Grunderna i Illustrator
    id: illustrator
    description: Hur skapar man en bild som kan skala sig till det oändliga? Här lär du dig att jobba i Illustrator.
    class: vektorteknik
    image: thumbnail_vektorteknik.jpg
  - title: Grunderna i LESS
    id: less
    description: Optimera ditt arbetsflöde när du skriver CSS. Här visar vi hur man använder sig av LESS.
    class: less
    image: thumbnail_less.jpg
  - title: Grunderna i Git
    id: git
    description: I den här kursen förklarar vi hur Git fungerar och hur du kan använda det i ditt arbete.
    class: git
    image: thumbnail_git.jpg
  - title: Grunderna i SEO
    id: seo
    description: Hur hamnar man först i Google? I den här kursen ger vi tips på hur du kan åstadkomma det.
    class: seo
    image: thumbnail_seo.jpg