safe: false
lsi: false
name: Webbdesignkurser
markdown: kramdown
pygments: true


destination: ./_site/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: Webbdesignkurser
repo: website
branch: master

permalink:   /:categories/:title/

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

asset_pipeline:
 bundle: false